services:
  pg_db:
    container_name: pg_db
    image: postgres:15.4-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot_db
    volumes:
      - ./database/pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - bot

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    networks:
      - bot
    depends_on:
      - pg_db

#  web:
#    build: .
#    command: python bot/manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"
#    networks:
#      - bot

volumes:
  db:
  logs:

networks:
  bot:
    name: bot
    driver: bridge